name: Manual Arch Build (YAYMA)

on:
  workflow_dispatch:

jobs:
  build-arch:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: System Init
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git cmake ninja pkg-config gtk3 libsecret libsoup3 unzip curl wget clang llvm wpewebkit wpebackend-fdo libwpe rustup

      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Rust
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: rust-frb-2.12.0-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: rust-frb-2.12.0-

      - name: Setup Rust
        run: |
          rustup default stable
          echo "LIBCLANG_PATH=/usr/lib" >> $GITHUB_ENV
          echo "CLANG_PATH=/usr/bin/clang" >> $GITHUB_ENV
          echo "/root/.cargo/bin" >> $GITHUB_PATH

      - name: Install FRB Codegen
        run: |
          if ! command -v flutter_rust_bridge_codegen &> /dev/null; then
            cargo install flutter_rust_bridge_codegen --version 2.12.0
          fi
          echo "/root/.cargo/bin" >> $GITHUB_PATH

      - name: Install Flutter
        run: |
          git clone --depth 1 --single-branch https://github.com/flutter/flutter -b stable /opt/flutter
          /opt/flutter/bin/flutter precache --linux --no-android --no-ios --no-web --no-fuchsia
          echo "/opt/flutter/bin" >> $GITHUB_PATH

      - name: Build
        working-directory: ./frontend
        run: |
          export PATH="$PATH:/opt/flutter/bin:/root/.cargo/bin"
          flutter config --no-analytics
          flutter pub get
          flutter_rust_bridge_codegen generate
          flutter build linux --release --no-pub

      - name: Archive
        run: tar -czvf linux_release.tar.gz -C build/linux/x64/release/bundle/ .

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: linux_release
          path: linux_release.tar.gz
