name: Build Release

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    env:
      RUSTFLAGS: -C link-arg=-fuse-ld=lld
      CC: clang
      CXX: clang++
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: System Init
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build pkg-config libgtk-3-dev libsecret-1-dev libsoup-3.0-dev libwebkit2gtk-4.1-dev libasound2-dev curl git unzip clang lld libclang-dev llvm-dev libayatana-appindicator3-dev libdbus-1-dev

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rust-src

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "src/rust -> src/target"
          key: "6e00177713e85d9e34ffa4f19e3a67d4c93a1854"

      - name: Install Tools
        run: |
          if [ ! -f "$HOME/.cargo/bin/cargo-binstall" ]; then
            curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          fi
          cargo install flutter_rust_bridge_codegen --git https://github.com/fzyzcjy/flutter_rust_bridge.git --rev 6e00177713e85d9e34ffa4f19e3a67d4c93a1854
          cargo binstall -y cargo-expand

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Build
        working-directory: ./src
        run: |
          flutter config --no-analytics
          flutter pub get
          flutter_rust_bridge_codegen generate
          flutter build linux --release

      - name: Archive
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          if [ "$VERSION" == "$GITHUB_REF" ]; then VERSION="manual"; fi
          tar -czvf yayma-linux-${VERSION}.tar.gz -C src/build/linux/x64/release/bundle/ .

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: linux_release
          path: yayma-linux-*.tar.gz

  build-windows:
    runs-on: windows-latest
    env:
      RUSTFLAGS: -C linker=lld-link.exe
      CC: clang
      CXX: clang++
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rust-src

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "src/rust -> src/target"
          key: "6e00177713e85d9e34ffa4f19e3a67d4c93a1854"

      - name: Install Tools
        run: |
          if ((Test-Path "$HOME\.cargo\bin\cargo-binstall.exe") -eq $false) {
            curl.exe -L --proto "=https" --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.ps1 -o install-binstall.ps1
            powershell -ExecutionPolicy RemoteSigned -File install-binstall.ps1 -Force
          }
          cargo install flutter_rust_bridge_codegen --git https://github.com/fzyzcjy/flutter_rust_bridge.git --rev 6e00177713e85d9e34ffa4f19e3a67d4c93a1854
          cargo binstall -y cargo-expand
        shell: powershell

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Build
        working-directory: ./src
        run: |
          flutter config --no-analytics
          flutter pub get
          flutter_rust_bridge_codegen generate
          flutter build windows --release
        shell: powershell

      - name: Archive
        run: |
          $VERSION = $env:GITHUB_REF -replace 'refs/tags/v', ''
          if ($VERSION -eq $env:GITHUB_REF) { $VERSION = "manual" }
          Compress-Archive -Path "src\build\windows\x64\runner\Release\*" -DestinationPath "yayma-windows-$VERSION.zip"
        shell: powershell

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: windows_release
          path: yayma-windows-*.zip

  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: System Init
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build pkg-config libgtk-3-dev libsecret-1-dev libsoup-3.0-dev libwebkit2gtk-4.1-dev libasound2-dev curl git unzip clang lld libclang-dev llvm-dev libayatana-appindicator3-dev libdbus-1-dev

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android, armv7-linux-androideabi, x86_64-linux-android
          components: rust-src

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "src/rust -> src/target"
          key: "6e00177713e85d9e34ffa4f19e3a67d4c93a1854"

      - name: Install Tools
        run: |
          if [ ! -f "$HOME/.cargo/bin/cargo-binstall" ]; then
            curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          fi
          cargo install flutter_rust_bridge_codegen --git https://github.com/fzyzcjy/flutter_rust_bridge.git --rev 6e00177713e85d9e34ffa4f19e3a67d4c93a1854
          cargo binstall -y cargo-expand

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Build
        working-directory: ./src
        run: |
          flutter config --no-analytics
          flutter pub get
          flutter_rust_bridge_codegen generate
          flutter build apk --release --split-per-abi

      - name: Archive
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          if [ "$VERSION" == "$GITHUB_REF" ]; then VERSION="manual"; fi
          mkdir -p android_artifacts
          for apk in src/build/app/outputs/flutter-apk/app-*-release.apk; do
            abi=$(basename "$apk" | sed -E 's/app-(.*)-release\.apk/\1/')
            cp "$apk" "android_artifacts/yayma-android-${abi}-${VERSION}.apk"
          done

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: android_release
          path: android_artifacts/yayma-android-*.apk
